### ISSUE TITLE
Ability to remove/replace CBFS files

### ISSUE THREAD

**Issue by kylerankin** [osresearch/flashtools#7]
Enhancement request for https://github.com/osresearch/flashtools/blob/master/cbfs.c

Both on a live ROM and a local ROM image it would be useful to remove or replace files. Currently we can only add files, which means once a keyring exists in CBFS we can't modify it without a vanilla ROM.

**Comment by flammit** [comment]
Agreed.  As a workaround right now, you can always just start with the clean reproducible ROM file and in Heads do `flash.sh -c clean.rom` which will not carry forward the previous config (effectively removing it).

**Comment by kylerankin** [comment]
Thank you. In my case I added read functionality to flash.sh in PR #411 (https://github.com/osresearch/heads/pull/411/commits/a9bf4eb8740a6eb3cf6d17cb9d531259a7c6b70d) so I could copy down the running image, modify it, and flash it back, so I'm attempting to do this without a clean ROM to work from.

**Comment by flammit** [comment]
Would just having a `remove` capability on local files be okay for now?  It's pretty straight forward to replace that CBFS file with a new empty section, but you should also recombine contiguous "empty" sections back into the largest blocks possible.

**Comment by kylerankin** [comment]
Yes, just having remove capability on local files would be all I would need. Then I could implement replace myself with a combination of remove and add.

**Comment by flammit** [comment]
@kylerankin please test out PR #6 when you get a chance. It now has a cbfs delete option: `cbfs -o coreboot.rom -d cbfs_file_name`

**Comment by kylerankin** [comment]
@flammit I've tested this and it works for me!
